#!/bin/sh

### START Methods ###
start_app1() {
	echo "Starting app1"
	sleep 2
}

start_app2() {
	echo "Starting app2"
	sleep 2
}

start_all(){
	echo "Starting ALL"
	start_app1
	start_app2
}

### STOP Methods ###

stop_app1() {
	echo "Stopping app1"
	sleep 2
}

stop_app2() {
	echo "Stopping app2"
	sleep 2
}

stop_all(){
	echo "Stopping ALL"
	stop_app1
	stop_app2
}

### MENU ###
echo "-----`/bin/date`-----"

usage () {
   echo "Usage: $0 {stop|start} {app1|app2|all}"
   exit 1
}

case $1 in
start)
  case $2 in
    app1)
      $1_$2
      ;;
    app2)
      $1_$2
      ;;
    all)
      $1_$2
      ;;
    *)
      usage
      ;;
    esac
  ;;
stop)
  LOG=$STOP_LOG
  case $2 in
    app1)
      $1_$2
      ;;
    app2)
      $1_$2
      ;;
    all)
      $1_$2
      ;;
    *)
      usage
      ;;
    esac
  ;;
test)
  test
  ;;
*)
  usage
  ;;
esac


exit ${ERROR}

